version: '3.8'

volumes:
  homebridge-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./volumes/homebridge-beta-2.0.0

services:
  homebridge:
    build:
      context: .
      dockerfile: Dockerfile-beta-2.0.0
    container_name: homebridge-beta-2.0.0-waveshare
    # restart: unless-stopped
    network_mode: host
    volumes:
      - homebridge-data:/homebridge
    environment:
      - TZ=Europe/London # Change to your timezone
      - HOMEBRIDGE_PORT=8581
    ports:
      - '8581:8581' # Expose the Homebridge UI port
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'
